[package]
name = "emulato-rs"
version = "0.1.0"
authors = ["Felix Gruber <felgru@posteo.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
minifb = "0.19.3"
rand = "0.8"
rand_chacha = "0.3"
