[package]
name = "emulato-rs"
version = "0.1.0"
authors = ["Felix Gruber <felgru@posteo.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.19.2"
rand = "0.8"
rand_chacha = "0.3"
